### ISSUE TITLE
Question: Can I use it?

### ISSUE THREAD

**Issue by szuniverse** [woutervanwijk/mopidy-websettings#16]
Hi

Can I use it via HTTP JSON-RPC API like mopidy core functions via websocket? https://docs.mopidy.com/en/latest/api/http/

**Comment by kingosticks** [comment]
No, there's no support for anything like that I'm afraid.

**Comment by szuniverse** [comment]
did you planning?

**Comment by kingosticks** [comment]
I am not planning. Something like that would belong in Mopidy itself (https://github.com/mopidy/mopidy/issues/502#issuecomment-76048894)
